### ISSUE TITLE
Wrong memory amount

### ISSUE THREAD

**Issue by hector-vido** [mr3project/mr3-run-k8s#2]
Hi guys, I am facing some issues in our Openshift cluster.

When I create a query the worker pod does not appear and the following message can be seen in the logs:

```
2022-12-30T20:04:44,847 ERROR [K8sResourceScheduler-4-1] ResourceScheduler: Wrong memory amount: 787682222735360 m
java.lang.NumberFormatException: null
```

The nodes have 768GB of memory.

I noticed the following log message when the nodes are recognized:

```
2022-12-30T19:54:44,689  INFO [OkHttp https://kubernetes.default.svc/...] ResourceScheduler: Worker Node joined: compute-12: 787682218639360m 95690m true, adjusted Resource = [0MB, 95690m]
2022-12-30T19:54:44,691 ERROR [OkHttp https://kubernetes.default.svc/...] ResourceScheduler: Wrong memory amount: 787682226831360 m
java.lang.NumberFormatException: null
        at com.datamonad.mr3.container.k8s.NodesSnapshotStore.memoryUnit(NodesSnapshotStore.scala:203) ~[mr3-tez-1.0-assembly.jar:1.0]
        at com.datamonad.mr3.container.k8s.NodesSnapshotStore.com$datamonad$mr3$container$k8s$NodesSnapshotStore$$parseMemory(NodesSnapshotStore.scala:180) ~[mr3-tez-1.0-assembly.jar:1.0]
```

Because of this, I think the application consider that no memory is available and the worker pod will never be created.
Also, I made it work in my lab cluster, a single master with 24GB of RAM  and 2 workers with 16GB.

Any ideas?

Best,

**Comment by hector-vido** [comment]
[mr3master.tar.gz](https://github.com/mr3project/mr3-run-k8s/files/10326318/mr3master.tar.gz)

**Comment by hector-vido** [comment]
I found it, after the change in the kubelet memory reservation to a decimal number, the node metric that fabric8 pulls is in a strange format.

**Comment by mr3project** [comment]
Sorry, we haven't checked github issues. For discussion, please MR3 slack or Google group.
